# Generated by Django 4.0 on 2022-01-03 20:45

import django.core.validators
from django.db import migrations, models
import uuid
import worc.apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=500, verbose_name='nome')),
                ('email', models.EmailField(max_length=500, unique=True, verbose_name='email')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[worc.apps.core.validators.validate_cpf], verbose_name='CPF')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='idade')),
                ('salary_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pretenção salarial')),
                ('immediate_availability', models.BooleanField(default=False, verbose_name='disponibilidade imediata')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
    ]
