# Generated by Django 4.0 on 2022-01-05 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de nascimento'),
            preserve_default=False,
        ),
    ]
